{% set name = "jless" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PaulJuliusMartinez/jless/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3f1168c9b2432f7f4fa9dd3c31b55e371ef9d6f822dc98a8cdce5318a112bf2d

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - jless --help

about:
  home: https://github.com/PaulJuliusMartinez/jless
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A command-line JSON viewer
  description: |
    A JSON viewer which replaces whatever combination of less, jq, cat and your editor
    you currently use for viewing JSON files.

extra:
  recipe-maintainers:
    - tdido
